### ISSUE TITLE
Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by yaytul** [aug70/node-markdown-pdf#1]
(node:1) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 2 end listeners added. Use emitter.setMaxListeners() to increase limit
(node:1) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: spawn /usr/local/lib/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
    at exports._errnoException (util.js:1029:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by aug70** [comment]
```eval "$(docker-machine env dev)"``` fixed issue.
